import LegalLayout from "@/components/sidekick/LegalLayout";

export const metadata = {
  title: "Terms of Service · Sidekick",
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" updated="April 29, 2026">
      <p>
        These Terms of Service ("Terms") govern your access to and use of the
        Sidekick service (the "Service") provided by Sidekick HQ, Inc.
        ("Sidekick," "we," "us," or "our"). By accessing or using the Service,
        you ("Customer," "you," or "your") agree to be bound by these Terms.
      </p>

      <h2>1. The Service</h2>
      <p>
        Sidekick provides a text-based assistant that ingests documents you
        provide (such as standard operating procedures, schedules, and
        policies) and answers questions from your designated end users
        ("Workers") over SMS and other supported channels. Specific features,
        usage limits, and supported channels may change over time.
      </p>

      <h2>2. Your account &amp; authority</h2>
      <p>
        You represent that you are authorized to enter into these Terms on
        behalf of your organization, that the information you provide is
        accurate, and that you will keep your account credentials secure. You
        are responsible for all activity under your account.
      </p>

      <h2>3. Customer content</h2>
      <p>
        "Customer Content" means the documents, data, and other materials you
        upload to the Service or that are generated by Workers' use of the
        Service. You retain all rights in Customer Content. You grant Sidekick
        a non-exclusive, worldwide license to host, process, and use Customer
        Content solely to provide and improve the Service for you. You are
        responsible for the legality and accuracy of Customer Content and for
        having the rights necessary to share it with us.
      </p>

      <h2>4. Acceptable use</h2>
      <p>
        You agree not to (a) use the Service in violation of applicable law;
        (b) attempt to reverse engineer, decompile, or otherwise derive the
        source code of the Service; (c) use the Service to send unsolicited
        commercial messages or to harass any person; (d) interfere with the
        integrity or performance of the Service; or (e) use the Service to
        process information for which you lack the right or consent.
      </p>

      <h2>5. AI-generated answers</h2>
      <p>
        The Service uses large language models and other automated systems to
        generate answers based on Customer Content. Automated answers may
        contain errors or omissions. You are responsible for reviewing and
        validating answers used in safety-critical, legal, medical, financial,
        or compliance contexts. Sidekick does not guarantee that any answer is
        accurate, complete, or fit for a particular purpose.
      </p>

      <h2>6. Fees</h2>
      <p>
        If you sign an order form or other written agreement with Sidekick,
        the fees and payment terms in that document apply. Otherwise, the
        Service may be provided to you under a free trial, pilot, or other
        arrangement that we may modify or terminate at any time.
      </p>

      <h2>7. Confidentiality</h2>
      <p>
        Each party will protect the other's non-public information disclosed
        in connection with the Service using at least the same degree of care
        it uses to protect its own confidential information of similar
        sensitivity, and in no event less than reasonable care. Confidential
        information does not include information that is or becomes public
        without breach of these Terms, was already lawfully known to the
        receiving party, or is independently developed without use of the
        disclosing party's information.
      </p>

      <h2>8. Term &amp; termination</h2>
      <p>
        These Terms remain in effect while you use the Service. Either party
        may terminate the relationship at any time on written notice. We may
        suspend or terminate the Service immediately if you breach these
        Terms or if we reasonably believe continued provision of the Service
        creates a legal or security risk. On termination, your right to use
        the Service ends and we may delete Customer Content after a
        commercially reasonable period.
      </p>

      <h2>9. Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE." TO THE MAXIMUM
        EXTENT PERMITTED BY LAW, SIDEKICK DISCLAIMS ALL WARRANTIES, EXPRESS OR
        IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
        PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SIDEKICK DOES NOT WARRANT
        THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF
        HARMFUL COMPONENTS.
      </p>

      <h2>10. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEITHER PARTY WILL BE LIABLE
        FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
        DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES. EACH PARTY'S TOTAL
        LIABILITY ARISING OUT OF OR RELATING TO THESE TERMS WILL NOT EXCEED
        THE GREATER OF (A) THE FEES PAID OR PAYABLE BY YOU TO SIDEKICK IN THE
        TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO LIABILITY OR
        (B) ONE HUNDRED U.S. DOLLARS ($100).
      </p>

      <h2>11. Indemnification</h2>
      <p>
        You agree to defend, indemnify, and hold harmless Sidekick and its
        officers, directors, employees, and agents from and against any
        claims, damages, liabilities, and expenses (including reasonable
        attorneys' fees) arising out of or related to (a) your Customer
        Content, (b) your use of the Service in violation of these Terms or
        applicable law, or (c) your violation of the rights of any third
        party.
      </p>

      <h2>12. Governing law</h2>
      <p>
        These Terms are governed by the laws of the State of California,
        without regard to its conflict-of-laws principles. The state and
        federal courts located in San Francisco County, California will have
        exclusive jurisdiction over any dispute arising out of or relating to
        these Terms, and each party consents to the personal jurisdiction of
        those courts.
      </p>

      <h2>13. Changes</h2>
      <p>
        We may update these Terms from time to time. If we make material
        changes, we will provide reasonable notice (for example, by email or
        in-product notice). Your continued use of the Service after the
        effective date of an update constitutes acceptance of the updated
        Terms.
      </p>

      <h2>14. Contact</h2>
      <p>
        Questions about these Terms? Email{" "}
        <a href="mailto:hello@textsidekick.com">hello@textsidekick.com</a> or
        write to Sidekick HQ, Inc., 1011 Washington Street, San Francisco,
        CA.
      </p>
    </LegalLayout>
  );
}
